export const FETCH_STOCKS = 'FETCH_STOCKS'
export const LIST_CHANGE_STOCKS = 'LIST_CHANGE_STOCKS';
export const ORDER_STOCKS = 'ORDER_STOCKS';

export const FETCH_STOCKS_LIKE = 'FETCH_STOCKS_LIKE'
export const LIST_CHANGE_STOCKS_LIKE = 'LIST_CHANGE_STOCKS_LIKE';
export const ORDER_STOCKS_LIKE = 'ORDER_STOCKS_LIKE';